baseURL: https://example.com
languageCode: en
DefaultContentLanguage: en
title: Website of Sergio Wang
theme: anatole
summarylength: 10
enableEmoji: yes
enableRobotsTXT: yes
pygmentsUseClasses: yes
pygmentsCodeFences: yes
pygmentsCodefencesGuessSyntax: yes
markup:
  goldmark:
    renderer:
      unsafe: yes
